### ISSUE TITLE
Patch to make this plugin work on Moodle 4

### ISSUE THREAD

**Issue by zabellemotte** [benchen71/moodle-filter_toc#5]
Replace filter.php file with this one.
[filter_toc_patch.zip](https://github.com/benchen71/moodle-filter_toc/files/11121674/filter_toc_patch.zip)

**Comment by benchen71** [comment]
I am happy to merge your changes, but I am no longer working at an institution with a Moodle site so I cannot do any testing, sorry!

**Comment by benchen71** [comment]
New version released. Thanks for contributing!

**Comment by sangeeyeah** [comment]
Installed and tested on Moodle 4.1.3+ (Build: 20230602).

It is working as expected.

Will update if I come across any issues.

**Comment by zabellemotte** [comment]
I am happy to read the patch has been integrated, but I do not understand why the new version is not available on the plugin officiel page :
https://moodle.org/plugins/filter_toc/versions

**Comment by benchen71** [comment]
I have updated the moodle site with the latest version.
